<?php

namespace Concurso\Menus4AllBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListaCompraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListaCompraRepository extends EntityRepository {

    public function getIngredientesListaCompraDescartados($idsIngrediente, $idListaCompra) {
        $em = $this->getDoctrine()->getEntityManager();
        // Todas las recetas cuya id no se encuentra en el array recibido y pertenezca al menú actual
        $query = $em->createQuery("SELECT il FROM ConcursoMenus4AllBundle:IngredientesListaCompra il JOIN i.ConcursoMenus4AllBundle:ListaCompra l JOIN l.ConcursoMenus4AllBundle:Ingrediente i where i.id not in (:ids) AND l.id = :idListaCompra ")
                ->setParameter(array(
            "ids" => $idsIngrediente,
            "idListaCompra" => $idListaCompra
                )
        );

        return $query->getResult();
    }

}
