<?php

namespace Concurso\Menus4AllBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ValoracionMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoracionMenuRepository extends EntityRepository
{
}
