parameters:
    database_driver:   pdo_sqlite
    database_host:     localhost
    database_port:     ~
    database_path:     /home/ozram/Sitios/Symfony/src/Concurso/Menus4AllBundle/SQLiteDb/menus4all.db
    database_name:     menus4all
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            es
    secret:            ThisTokenIsNotSoSecretChangeIt
