cm4all_homepage:
    pattern:  /
    defaults: { _controller: ConcursoMenus4AllBundle:Main:index }


#Routing Menus
  
cm4all_menus_post:
   pattern: /menus
   defaults: { _controller: ConcursoMenus4AllBundle:Menus:createMenu }
   requirements:
     _method: POST
     _format: json

cm4all_menus_get:
   pattern: /menus/{id}
   defaults: { _controller: ConcursoMenus4AllBundle:Menus:readMenu }
   requirements:
     _method: GET
     _format: json
     
cm4all_menus_get_collection:
   pattern: /menus
   defaults: { _controller: ConcursoMenus4AllBundle:Menus:readMenusCollection }
   requirements:
     _method: GET
     _format: json

cm4all_menus_put:
   pattern: /menus/{id}
   defaults: { _controller: ConcursoMenus4AllBundle:Menus:updateMenu }
   requirements:
     _method: PUT
     _format: json
    
cm4all_menus_delete:
   pattern: /menus/{id}
   defaults: { _controller: ConcursoMenus4AllBundle:Menus:deleteMenu }
   requirements:
     _method: DELETE
     _format: json


#Routing Recetas
  
cm4all_recetas_index:
    pattern:  /recetas/hola
    defaults: { _controller: ConcursoMenus4AllBundle:Recetas:index }
    
cm4all_recetas_post:
   pattern: /recetas
   defaults: { _controller: ConcursoMenus4AllBundle:Recetas:createReceta }
   requirements:
     _method: POST
     _format: json

cm4all_recetas_get:
   pattern: /recetas/{id}
   defaults: { _controller: ConcursoMenus4AllBundle:Recetas:readReceta }
   requirements:
     _method: GET
     _format: json
     
cm4all_recetas_get_collection:
   pattern: /recetas
   defaults: { _controller: ConcursoMenus4AllBundle:Recetas:readRecetasCollection }
   requirements:
     _method: GET
     _format: json

cm4all_recetas_put:
   pattern: /recetas/{id}
   defaults: { _controller: ConcursoMenus4AllBundle:Recetas:updateReceta }
   requirements:
     _method: PUT
     _format: json
    
cm4all_recetas_delete:
   pattern: /recetas/{id}
   defaults: { _controller: ConcursoMenus4AllBundle:Recetas:deleteReceta }
   requirements:
     _method: DELETE
     _format: json
