parameters:
    cm4all.recetasmanager.class: Concurso\Menus4AllBundle\Services\RecetasManager
    doctrine: Doctrine\ORM\Mapping
    
services:
    cm4all.recetasmanager:
        class: %cm4all.recetasmanager.class%
        arguments: ["@doctrine.orm.entity_manager"]
