parameters:
    cm4all.recetasmanager.class: Concurso\Menus4AllBundle\Services\RecetasManager
    cm4all.menusmanager.class: Concurso\Menus4AllBundle\Services\MenusManager
    cm4all.listasCompramanager.class: Concurso\Menus4AllBundle\Services\ListasCompra
    cm4all.valoracionesMenumanager.class: Concurso\Menus4AllBundle\Services\ValoracionMenu
    
services:
    cm4all.recetasmanager:
        class: %cm4all.recetasmanager.class%
        arguments: ["@doctrine.orm.entity_manager", "@validator", "@translator"]

    cm4all.menusmanager:
        class: %cm4all.menusmanager.class%
        arguments: ["@doctrine.orm.entity_manager", "@validator"]
        
    cm4all.valoracionesMenumanager:
        class: %cm4all.valoracionesMenumanager.class%
        arguments: ["@doctrine.orm.entity_manager", "@validator"]
        
    cm4all.listasCompramanager:
        class: %cm4all.listasCompramanager.class%
        arguments: ["@doctrine.orm.entity_manager", "@validator"]
    sonata.cm4all.admin.receta:
       id: sonata.admin.course
       class: Concurso\Menus4AllBundle\Admin\RecetaAdmin
       tags:
          - { name: sonata.admin, manager_type: orm, group: 'Recetas', label: 'Receta' }
       arguments:
          - null
          - Concurso\Menus4AllBundle\Entity\Receta
          - ConcursoMenus4AllBundle:Admin